/**
 * Mock Data — Bioactiva CRM (Fase 1)
 * Datos representativos basados en el modelo nuevo
 */

import { Organization, Contact, Lead, Quote, Notification } from '@/src/types/crm';

// ──────────────────────────────────────────────
// ORGANIZACIONES
// ──────────────────────────────────────────────
export const mockOrganizations: Organization[] = [
  {
    id: 'ORG-2025-001',
    ruc: '20601258529',
    nombre: 'Altomayo',
    nombreCompleto: 'Industrias Mayo S.A.C.',
    tipo: 'Empresa',
    sector: 'Agroindustria / Café',
    tamano: 'Grande',
    ubicacion: 'Lima, Perú',
    actividades: 'Producción y comercialización de café peruano de especialidad',
    creadoEn: new Date('2025-01-10'),
  },
  {
    id: 'ORG-2025-002',
    ruc: '20524967627',
    nombre: 'Cacao de Aroma',
    nombreCompleto: 'Cacao de Aroma S.A.C.',
    area: 'Área de Innovación y Proyectos',
    tipo: 'Empresa',
    sector: 'Agroindustria / Cacao',
    tamano: 'Mediana',
    ubicacion: 'San Martín, Perú',
    actividades: 'Producción de cacao fino de aroma para exportación',
    creadoEn: new Date('2025-01-15'),
  },
  {
    id: 'ORG-2025-003',
    ruc: '20524967627',
    nombre: 'Municipalidad de Miraflores',
    nombreCompleto: 'Municipalidad Distrital de Miraflores',
    area: 'Gerencia de Desarrollo Económico',
    tipo: 'Entidad Pública',
    sector: 'Gobierno Local',
    tamano: 'Grande',
    ubicacion: 'Miraflores, Lima',
    creadoEn: new Date('2025-02-01'),
  },
  {
    id: 'ORG-2025-004',
    nombre: 'AgroTech Innova',
    tipo: 'Startup',
    sector: 'Agtech / Tecnología Agrícola',
    tamano: 'Micro',
    ubicacion: 'Lima, Perú',
    actividades: 'Desarrollo de soluciones digitales para el agro peruano',
    creadoEn: new Date('2025-02-20'),
  },
  {
    id: 'ORG-2025-005',
    nombre: 'Inversiones Pisco S.A.',
    tipo: 'Empresa',
    sector: 'Alimentos y Bebidas',
    tamano: 'Mediana',
    ubicacion: 'Ica, Perú',
    creadoEn: new Date('2025-04-01'),
  },
  {
    id: 'ORG-2025-006',
    nombre: 'Constructora del Sur',
    tipo: 'Empresa',
    sector: 'Construcción',
    tamano: 'Grande',
    ubicacion: 'Arequipa, Perú',
    creadoEn: new Date('2025-03-10'),
  },
];

// ──────────────────────────────────────────────
// CONTACTOS
// ──────────────────────────────────────────────
export const mockContacts: Contact[] = [
  // ── Altomayo (ORG-2025-001) — 8 contactos ──────────────────────────
  {
    id: 'CON-2025-001',
    organizacionId: 'ORG-2025-001',
    vocativo: 'Sr.',
    nombres: 'Ricardo',
    apellidos: 'Perales Tuesta',
    correo1: 'rperales@altomayo.com.pe',
    telefono: '997 654 321',
    cargo: 'Gerente de Proyectos',
    creadoEn: new Date('2025-01-10'),
  },
  {
    id: 'CON-2025-002',
    organizacionId: 'ORG-2025-001',
    vocativo: 'Sra.',
    nombres: 'Lucía',
    apellidos: 'Huanca Ríos',
    correo1: 'lhuanca@altomayo.com.pe',
    telefono: '991 234 567',
    cargo: 'Jefa de Innovación',
    creadoEn: new Date('2025-01-12'),
  },
  {
    id: 'CON-2025-009',
    organizacionId: 'ORG-2025-001',
    vocativo: 'Sr.',
    nombres: 'Héctor',
    apellidos: 'Sánchez Ruiz',
    correo1: 'hsanchez@altomayo.com.pe',
    telefono: '993 111 456',
    cargo: 'Gerente Comercial',
    creadoEn: new Date('2025-01-15'),
  },
  {
    id: 'CON-2025-010',
    organizacionId: 'ORG-2025-001',
    vocativo: 'Sra.',
    nombres: 'Patricia',
    apellidos: 'Ccopa Mamani',
    correo1: 'pccopa@altomayo.com.pe',
    telefono: '945 887 234',
    cargo: 'Gerente de Operaciones',
    creadoEn: new Date('2025-01-20'),
  },
  {
    id: 'CON-2025-011',
    organizacionId: 'ORG-2025-001',
    vocativo: 'Sr.',
    nombres: 'Javier',
    apellidos: 'Medina Tapia',
    correo1: 'jmedina@altomayo.com.pe',
    cargo: 'Jefe de Calidad',
    creadoEn: new Date('2025-02-01'),
  },
  {
    id: 'CON-2025-012',
    organizacionId: 'ORG-2025-001',
    vocativo: 'Srta.',
    nombres: 'Valeria',
    apellidos: 'Torres Aquino',
    correo1: 'vtorres@altomayo.com.pe',
    telefono: '998 302 177',
    cargo: 'Coordinadora de Proyectos I+D',
    creadoEn: new Date('2025-02-10'),
  },
  {
    id: 'CON-2025-013',
    organizacionId: 'ORG-2025-001',
    vocativo: 'Sr.',
    nombres: 'Ernesto',
    apellidos: 'Villanueva Ríos',
    correo1: 'evillanueva@altomayo.com.pe',
    telefono: '944 560 012',
    cargo: 'Subgerente de Finanzas',
    creadoEn: new Date('2025-02-18'),
  },
  {
    id: 'CON-2025-014',
    organizacionId: 'ORG-2025-001',
    vocativo: 'Sra.',
    nombres: 'Carmen',
    apellidos: 'Delgado Ponce',
    correo1: 'cdelgado@altomayo.com.pe',
    cargo: 'Asistente de Gerencia',
    creadoEn: new Date('2025-03-01'),
  },

  // ── Cacao de Aroma (ORG-2025-002) — 4 contactos ────────────────────
  {
    id: 'CON-2025-003',
    organizacionId: 'ORG-2025-002',
    vocativo: 'Sr.',
    nombres: 'Carlos',
    apellidos: 'Vargas Díaz',
    correo1: 'cvargas@cacaodearoma.pe',
    telefono: '942 111 222',
    cargo: 'Director Ejecutivo',
    comentarios: 'Contacto principal desde mayo 2024',
    creadoEn: new Date('2025-01-15'),
  },
  {
    id: 'CON-2025-015',
    organizacionId: 'ORG-2025-002',
    vocativo: 'Sra.',
    nombres: 'Milagros',
    apellidos: 'Panduro Reátegui',
    correo1: 'mpanduro@cacaodearoma.pe',
    telefono: '965 432 100',
    cargo: 'Responsable de Exportaciones',
    creadoEn: new Date('2025-01-18'),
  },
  {
    id: 'CON-2025-016',
    organizacionId: 'ORG-2025-002',
    vocativo: 'Sr.',
    nombres: 'Joel',
    apellidos: 'Arévalo Pinchi',
    correo1: 'jarevalo@cacaodearoma.pe',
    cargo: 'Técnico Agrónomo',
    creadoEn: new Date('2025-02-05'),
  },
  {
    id: 'CON-2025-017',
    organizacionId: 'ORG-2025-002',
    vocativo: 'Sra.',
    nombres: 'Susana',
    apellidos: 'Navarro Castro',
    correo1: 'snavarro@cacaodearoma.pe',
    telefono: '941 009 873',
    cargo: 'Coordinadora de Proyectos',
    creadoEn: new Date('2025-02-12'),
  },

  // ── Municipalidad de Miraflores (ORG-2025-003) — 4 contactos ───────
  {
    id: 'CON-2025-004',
    organizacionId: 'ORG-2025-003',
    vocativo: 'Lic.',
    nombres: 'Roxana',
    apellidos: 'Salcedo Mora',
    correo1: 'rsalcedo@miraflores.gob.pe',
    telefono: '01 617-7272',
    cargo: 'Sub-Gerente de Desarrollo Económico',
    creadoEn: new Date('2025-02-01'),
  },
  {
    id: 'CON-2025-005',
    organizacionId: 'ORG-2025-003',
    vocativo: 'Sr.',
    nombres: 'Marco',
    apellidos: 'Quispe Benites',
    correo1: 'mquispe@miraflores.gob.pe',
    cargo: 'Asistente de Proyectos',
    creadoEn: new Date('2025-02-05'),
  },
  {
    id: 'CON-2025-018',
    organizacionId: 'ORG-2025-003',
    vocativo: 'Sr.',
    nombres: 'Fernando',
    apellidos: 'Chávez Lazo',
    correo1: 'fchavez@miraflores.gob.pe',
    telefono: '01 617-7273',
    cargo: 'Gerente de Desarrollo Económico',
    creadoEn: new Date('2025-02-08'),
  },
  {
    id: 'CON-2025-019',
    organizacionId: 'ORG-2025-003',
    vocativo: 'Sra.',
    nombres: 'Diana',
    apellidos: 'Pizarro Lozano',
    correo1: 'dpizarro@miraflores.gob.pe',
    cargo: 'Especialista en Tributación',
    creadoEn: new Date('2025-02-15'),
  },

  // ── AgroTech Innova (ORG-2025-004) — 3 contactos ───────────────────
  {
    id: 'CON-2025-006',
    organizacionId: 'ORG-2025-004',
    vocativo: 'Sr.',
    nombres: 'Andrés',
    apellidos: 'Flores Cárdenas',
    correo1: 'andres@agrotechinnova.pe',
    telefono: '987 000 111',
    cargo: 'CEO & Fundador',
    creadoEn: new Date('2025-02-20'),
  },
  {
    id: 'CON-2025-020',
    organizacionId: 'ORG-2025-004',
    vocativo: 'Srta.',
    nombres: 'Fiorella',
    apellidos: 'Ríos Castillo',
    correo1: 'frios@agrotechinnova.pe',
    telefono: '986 543 210',
    cargo: 'CTO',
    creadoEn: new Date('2025-02-22'),
  },
  {
    id: 'CON-2025-021',
    organizacionId: 'ORG-2025-004',
    vocativo: 'Sr.',
    nombres: 'Bruno',
    apellidos: 'Garay Salas',
    correo1: 'bgaray@agrotechinnova.pe',
    cargo: 'Desarrollador de Negocios',
    creadoEn: new Date('2025-03-01'),
  },

  // ── Inversiones Pisco (ORG-2025-005) — 3 contactos ─────────────────
  {
    id: 'CON-2025-007',
    organizacionId: 'ORG-2025-005',
    vocativo: 'Sr.',
    nombres: 'Rafael',
    apellidos: 'Benavides Sotelo',
    correo1: 'rbenavides@invpisco.pe',
    telefono: '056 234 567',
    cargo: 'Gerente General',
    creadoEn: new Date('2025-04-01'),
  },
  {
    id: 'CON-2025-022',
    organizacionId: 'ORG-2025-005',
    vocativo: 'Sra.',
    nombres: 'Claudia',
    apellidos: 'Morán Vidal',
    correo1: 'cmoran@invpisco.pe',
    telefono: '056 234 568',
    cargo: 'Gerente de Producción',
    creadoEn: new Date('2025-04-03'),
  },
  {
    id: 'CON-2025-023',
    organizacionId: 'ORG-2025-005',
    vocativo: 'Sr.',
    nombres: 'Álvaro',
    apellidos: 'Espinoza Meza',
    correo1: 'aespinoza@invpisco.pe',
    cargo: 'Jefe de I+D',
    creadoEn: new Date('2025-04-05'),
  },

  // ── Constructora del Sur (ORG-2025-006) — 3 contactos ──────────────
  {
    id: 'CON-2025-008',
    organizacionId: 'ORG-2025-006',
    vocativo: 'Sr.',
    nombres: 'Gustavo',
    apellidos: 'Zúñiga Paredes',
    correo1: 'gzuniga@constructorasur.pe',
    telefono: '054 321 987',
    cargo: 'Gerente de Proyectos',
    creadoEn: new Date('2025-03-10'),
  },
  {
    id: 'CON-2025-024',
    organizacionId: 'ORG-2025-006',
    vocativo: 'Sra.',
    nombres: 'Alejandra',
    apellidos: 'Fuentes Cárdenas',
    correo1: 'afuentes@constructorasur.pe',
    telefono: '054 321 988',
    cargo: 'Jefa de Innovación y Digitalización',
    creadoEn: new Date('2025-03-12'),
  },
  {
    id: 'CON-2025-025',
    organizacionId: 'ORG-2025-006',
    vocativo: 'Sr.',
    nombres: 'Rodrigo',
    apellidos: 'Herrera Apaza',
    correo1: 'rherrera@constructorasur.pe',
    cargo: 'Coordinador Técnico',
    creadoEn: new Date('2025-03-15'),
  },
];

// ──────────────────────────────────────────────
// LEADS
// ──────────────────────────────────────────────
export const mockLeads: Lead[] = [
  {
    id: 'LEAD-2025-001',
    organizacionId: 'ORG-2025-001',
    contactoId: 'CON-2025-001',
    servicioInteres: 'Formulación de proyecto CONCYTEC',
    canal: 'Referido',
    encargado: 'Karien Diaz',
    encargadoEmail: 'karien@bioactiva.pe',
    estado: 'cerrado_ganado',
    desafioOportunidad: 'Postular a fondo concursable para innovación en procesamiento de café',
    proximaActividad: 'Cierre de expediente final',
    fechaProximaActividad: new Date('2025-05-15'),
    historial: 'Cliente con proyecto aprobado en convocatoria CONCYTEC 2024. Satisfecho con el servicio.',
    actividades: [
      {
        id: 'ACT-001',
        tipo: 'reunion',
        estado: 'realizada',
        nota: 'Reunión inicial. Cliente interesado en fondos concursables para I+D en café.',
        responsable: 'Karien Diaz',
        fecha: new Date('2025-01-12'),
        fechaCompletada: new Date('2025-01-12'),
      },
      {
        id: 'ACT-002',
        tipo: 'email',
        estado: 'realizada',
        nota: 'Envío de propuesta técnica y cotización (COT-2025-001).',
        responsable: 'Karien Diaz',
        fecha: new Date('2025-01-20'),
        fechaCompletada: new Date('2025-01-20'),
      },
    ],
    creadoEn: new Date('2025-01-10'),
  },
  {
    id: 'LEAD-2025-002',
    organizacionId: 'ORG-2025-002',
    contactoId: 'CON-2025-003',
    servicioInteres: 'Formulación de proyecto cadena de valor cacao fino',
    canal: 'Evento sectorial',
    encargado: 'Administración',
    estado: 'en_proceso',
    desafioOportunidad: 'Acceder a financiamiento para mejorar cadena productiva y exportar a mercados premium',
    proximaActividad: 'Seguimiento a propuesta enviada',
    fechaProximaActividad: new Date('2025-05-10'),
    historial: 'Incluye diagnóstico de cadena y perfil de proyecto. En evaluación.',
    actividades: [
      {
        id: 'ACT-003',
        tipo: 'llamada',
        estado: 'realizada',
        nota: 'Llamada de presentación de servicios. Interés confirmado.',
        responsable: 'Administración',
        fecha: new Date('2025-01-18'),
        fechaCompletada: new Date('2025-01-18'),
      },
      {
        id: 'ACT-004',
        tipo: 'email',
        estado: 'pendiente',
        nota: 'Envío de propuesta (COT-2025-002). Pendiente respuesta.',
        responsable: 'Administración',
        fecha: new Date('2025-02-05'),
      },
    ],
    creadoEn: new Date('2025-01-15'),
  },
  {
    id: 'LEAD-2025-003',
    organizacionId: 'ORG-2025-003',
    contactoId: 'CON-2025-004',
    servicioInteres: 'Beneficios tributarios Ley 30309',
    canal: 'Web / Redes sociales',
    encargado: 'Karien Diaz',
    encargadoEmail: 'karien@bioactiva.pe',
    estado: 'nuevo',
    desafioOportunidad: 'Levantamiento de gastos en I+D de proyectos municipales para deducción tributaria',
    proximaActividad: 'Reunión con Sub-Gerencia de Finanzas',
    fechaProximaActividad: new Date('2025-05-08'),
    historial: 'Incluye levantamiento de gastos en I+D y elaboración de expediente técnico Ley 30309.',
    actividades: [
      {
        id: 'ACT-005',
        tipo: 'reunion',
        estado: 'pendiente',
        nota: 'Presentación de servicios ante Sub-Gerencia. Solicitan cotización detallada.',
        responsable: 'Karien Diaz',
        fecha: new Date('2025-03-10'),
      },
    ],
    creadoEn: new Date('2025-02-01'),
  },
  {
    id: 'LEAD-2025-004',
    organizacionId: 'ORG-2025-004',
    contactoId: 'CON-2025-006',
    servicioInteres: 'Consultoría en formulación de proyectos de innovación',
    canal: 'LinkedIn',
    encargado: 'Karien Diaz',
    encargadoEmail: 'karien@bioactiva.pe',
    estado: 'nuevo',
    desafioOportunidad: 'Startup busca estructurar sus proyectos de I+D para postular a STARTUP PERÚ',
    historial: 'Contacto inicial vía LinkedIn. Pendiente primera reunión.',
    actividades: [],
    creadoEn: new Date('2025-04-01'),
  },
  {
    id: 'LEAD-2025-005',
    organizacionId: 'ORG-2025-005',
    contactoId: 'CON-2025-007',
    servicioInteres: 'Ley 30309 - Deducción I+D+i',
    canal: 'Referido',
    encargado: 'Luis Torres',
    estado: 'en_proceso',
    proximaActividad: 'Revisión de sustento técnico',
    fechaProximaActividad: new Date('2025-05-20'),
    actividades: [
      {
        id: 'ACT-006',
        tipo: 'reunion',
        estado: 'realizada',
        nota: 'Visita a planta para identificar proyectos de mejora tecnológica.',
        responsable: 'Luis Torres',
        fecha: new Date('2025-04-10'),
      }
    ],
    creadoEn: new Date('2025-04-05'),
  },
  {
    id: 'LEAD-2025-006',
    organizacionId: 'ORG-2025-006',
    contactoId: 'CON-2025-008',
    servicioInteres: 'Formulación de proyecto ProInnóvate',
    canal: 'Web',
    encargado: 'Ana Rojas',
    estado: 'cerrado_perdido',
    desafioOportunidad: 'Proyecto de digitalización de procesos.',
    historial: 'Cliente decidió postergar la inversión por temas presupuestales internos.',
    actividades: [],
    creadoEn: new Date('2025-03-20'),
  },

  // ── Leads adicionales Altomayo (ORG-2025-001) ──────────────────────
  {
    id: 'LEAD-2025-007',
    organizacionId: 'ORG-2025-001',
    contactoId: 'CON-2025-009',
    servicioInteres: 'Ley 30309 — Deducción gastos I+D exportación',
    canal: 'Referido',
    encargado: 'Karien Diaz',
    encargadoEmail: 'karien@bioactiva.pe',
    estado: 'cerrado_ganado',
    desafioOportunidad: 'Recuperar hasta 175% de gastos en investigación de nuevas variedades de café',
    historial: 'Expediente técnico aprobado por CONCYTEC. Deducción tributaria aplicada correctamente.',
    fechaCierre: new Date('2024-11-30'),
    actividades: [
      {
        id: 'ACT-010',
        tipo: 'reunion',
        estado: 'realizada',
        nota: 'Diagnóstico inicial de gastos I+D en planta Moyobamba.',
        responsable: 'Karien Diaz',
        fecha: new Date('2024-09-05'),
        fechaCompletada: new Date('2024-09-05'),
      },
      {
        id: 'ACT-011',
        tipo: 'email',
        estado: 'realizada',
        nota: 'Envío de expediente técnico a CONCYTEC para calificación.',
        responsable: 'Karien Diaz',
        fecha: new Date('2024-10-15'),
        fechaCompletada: new Date('2024-10-15'),
      },
      {
        id: 'ACT-012',
        tipo: 'llamada',
        estado: 'realizada',
        nota: 'Confirmación de aprobación. Cliente muy satisfecho.',
        responsable: 'Karien Diaz',
        fecha: new Date('2024-11-28'),
        fechaCompletada: new Date('2024-11-28'),
      },
    ],
    creadoEn: new Date('2024-09-01'),
  },
  {
    id: 'LEAD-2025-008',
    organizacionId: 'ORG-2025-001',
    contactoId: 'CON-2025-010',
    servicioInteres: 'Diagnóstico de innovación y hoja de ruta tecnológica',
    canal: 'Prospección directa',
    encargado: 'Administración',
    estado: 'en_proceso',
    desafioOportunidad: 'Mapear capacidades tecnológicas para escalar producción de café specialty',
    historial: 'En proceso de levantamiento de información. Segunda visita programada.',
    fechaCierre: new Date('2025-07-30'),
    proximaActividad: 'Segunda visita técnica a planta',
    fechaProximaActividad: new Date('2025-05-20'),
    actividades: [
      {
        id: 'ACT-013',
        tipo: 'reunion',
        estado: 'realizada',
        nota: 'Reunión de kick-off con Gerencia de Operaciones.',
        responsable: 'Administración',
        fecha: new Date('2025-03-10'),
        fechaCompletada: new Date('2025-03-10'),
      },
      {
        id: 'ACT-014',
        tipo: 'reunion',
        estado: 'pendiente',
        nota: 'Segunda visita técnica — revisión de procesos de tostado y empaque.',
        responsable: 'Administración',
        fecha: new Date('2025-05-20'),
      },
    ],
    creadoEn: new Date('2025-03-05'),
  },
  {
    id: 'LEAD-2025-009',
    organizacionId: 'ORG-2025-001',
    contactoId: 'CON-2025-002',
    servicioInteres: 'Formulación de proyecto FINCyT — Innovación en packaging sostenible',
    canal: 'Red profesional',
    encargado: 'Karien Diaz',
    encargadoEmail: 'karien@bioactiva.pe',
    estado: 'nuevo',
    desafioOportunidad: 'Desarrollar empaques biodegradables para exportación a mercados europeos con exigencias de sostenibilidad',
    historial: 'Reunión preliminar realizada. Esperando definición de presupuesto interno.',
    proximaActividad: 'Presentación de propuesta técnica',
    fechaProximaActividad: new Date('2025-06-05'),
    actividades: [
      {
        id: 'ACT-015',
        tipo: 'reunion',
        estado: 'realizada',
        nota: 'Presentación de servicios ante área de Innovación. Interés alto.',
        responsable: 'Karien Diaz',
        fecha: new Date('2025-04-22'),
        fechaCompletada: new Date('2025-04-22'),
      },
    ],
    creadoEn: new Date('2025-04-20'),
  },

  // ── Leads adicionales Cacao de Aroma (ORG-2025-002) ────────────────
  {
    id: 'LEAD-2025-010',
    organizacionId: 'ORG-2025-002',
    contactoId: 'CON-2025-015',
    servicioInteres: 'Certificación de origen y trazabilidad para exportación',
    canal: 'Evento presencial',
    encargado: 'Ana Rojas',
    estado: 'cerrado_ganado',
    desafioOportunidad: 'Obtener certificación Fine Cacao and Chocolate para acceder a compradores premium en Europa',
    historial: 'Servicio completado. Cliente logró certificación y aumentó precio de venta en 30%.',
    fechaCierre: new Date('2024-12-15'),
    actividades: [
      {
        id: 'ACT-016',
        tipo: 'reunion',
        estado: 'realizada',
        nota: 'Taller de diagnóstico de trazabilidad en campo — San Martín.',
        responsable: 'Ana Rojas',
        fecha: new Date('2024-10-08'),
        fechaCompletada: new Date('2024-10-08'),
      },
      {
        id: 'ACT-017',
        tipo: 'email',
        estado: 'realizada',
        nota: 'Entrega de informe de trazabilidad y documentación para certificadora.',
        responsable: 'Ana Rojas',
        fecha: new Date('2024-11-20'),
        fechaCompletada: new Date('2024-11-20'),
      },
    ],
    creadoEn: new Date('2024-10-01'),
  },
  {
    id: 'LEAD-2025-011',
    organizacionId: 'ORG-2025-002',
    contactoId: 'CON-2025-017',
    servicioInteres: 'Formulación de proyecto AGROIDEAS — Fortalecimiento de cadena productiva',
    canal: 'Referido',
    encargado: 'Karien Diaz',
    encargadoEmail: 'karien@bioactiva.pe',
    estado: 'nuevo',
    desafioOportunidad: 'Acceder a cofinanciamiento del Programa AGROIDEAS para tecnificación de fermentación',
    proximaActividad: 'Primera reunión técnica',
    fechaProximaActividad: new Date('2025-05-28'),
    actividades: [],
    creadoEn: new Date('2025-05-01'),
  },

  // ── Lead AgroTech Innova (ORG-2025-004) ────────────────────────────
  {
    id: 'LEAD-2025-012',
    organizacionId: 'ORG-2025-004',
    contactoId: 'CON-2025-020',
    servicioInteres: 'Postulación a STARTUP PERÚ — Emprendimientos Innovadores',
    canal: 'LinkedIn',
    encargado: 'Luis Torres',
    estado: 'en_proceso',
    desafioOportunidad: 'Estructurar propuesta técnica y plan de negocio para concurso STARTUP PERÚ Gen 14',
    historial: 'Plan de negocio en desarrollo. Fecha límite de postulación: 30 junio 2025.',
    proximaActividad: 'Revisión de plan de negocio con CTO',
    fechaProximaActividad: new Date('2025-05-25'),
    actividades: [
      {
        id: 'ACT-018',
        tipo: 'reunion',
        estado: 'realizada',
        nota: 'Kick-off. Se define alcance: propuesta técnica + plan de negocios + pitch deck.',
        responsable: 'Luis Torres',
        fecha: new Date('2025-04-15'),
        fechaCompletada: new Date('2025-04-15'),
      },
      {
        id: 'ACT-019',
        tipo: 'reunion',
        estado: 'pendiente',
        nota: 'Revisión del borrador de plan de negocios.',
        responsable: 'Luis Torres',
        fecha: new Date('2025-05-25'),
      },
    ],
    creadoEn: new Date('2025-04-10'),
  },
];

// ──────────────────────────────────────────────
// COTIZACIONES
// ──────────────────────────────────────────────
export const mockQuotes: Quote[] = [
  {
    id: 'COT-2025-001',
    leadId: 'LEAD-2025-001',
    anio: 2025,
    mes: 'Enero',
    dirigidoA: 'Ricardo Perales Tuesta',
    fechaCotizacion: new Date('2025-01-20'),
    cliente: 'Industrias Mayo S.A.C. (Altomayo)',
    producto: 'Innovasuys',
    servicio: 'Formulación de proyecto para fondo concursable CONCYTEC — I+D en café',
    monto: 12500,
    moneda: 'PEN',
    estado: 'aceptada',
    remitente: 'Karien Diaz',
    observacion: 'Proyecto aprobado. Cliente muy satisfecho. Referencia para futuras propuestas.',
    linkPropuesta: 'https://drive.google.com/propuesta-altomayo-2025',
    creadoEn: new Date('2025-01-20'),
  },
  {
    id: 'COT-2025-002',
    leadId: 'LEAD-2025-002',
    anio: 2025,
    mes: 'Febrero',
    dirigidoA: 'Carlos Vargas Díaz',
    fechaCotizacion: new Date('2025-02-05'),
    cliente: 'Cacao de Aroma S.A.C.',
    producto: 'Innovasuys',
    servicio: 'Formulación de proyecto para cadena de valor cacao fino de aroma',
    monto: 9800,
    moneda: 'PEN',
    estado: 'enviada',
    remitente: 'Administración',
    observacion: 'Incluye diagnóstico de cadena y perfil de proyecto para financiamiento sectorial.',
    linkPropuesta: 'https://drive.google.com/propuesta-cacaodearoma-2025',
    creadoEn: new Date('2025-02-05'),
  },
  {
    id: 'COT-2025-003',
    leadId: 'LEAD-2025-003',
    anio: 2025,
    mes: 'Marzo',
    dirigidoA: 'Roxana Salcedo Mora',
    fechaCotizacion: new Date('2025-03-15'),
    cliente: 'Municipalidad Distrital de Miraflores',
    producto: 'Consultoría Tributaria',
    servicio: 'Formulación de proyecto para beneficios tributarios Ley 30309 — Gastos en I+D',
    monto: 15000,
    moneda: 'PEN',
    estado: 'pendiente',
    remitente: 'Karien Diaz',
    observacion: 'Incluye levantamiento de gastos en I+D y expediente técnico completo.',
    creadoEn: new Date('2025-03-15'),
  },

  // ── Cotizaciones Altomayo — Ley 30309 (LEAD-2025-007) ──────────────
  {
    id: 'COT-2024-001',
    leadId: 'LEAD-2025-007',
    anio: 2024,
    mes: 'Setiembre',
    dirigidoA: 'Héctor Sánchez Ruiz',
    fechaCotizacion: new Date('2024-09-10'),
    cliente: 'Industrias Mayo S.A.C. (Altomayo)',
    producto: 'Consultoría Tributaria',
    servicio: 'Calificación y expediente técnico Ley 30309 — Deducción I+D en exportación de café',
    monto: 8900,
    moneda: 'PEN',
    estado: 'aceptada',
    remitente: 'Karien Diaz',
    observacion: 'Expediente aprobado por CONCYTEC. Deducción del 175% aplicada en DJ anual 2024.',
    linkPropuesta: 'https://drive.google.com/cot-altomayo-ley30309-2024',
    creadoEn: new Date('2024-09-10'),
  },

  // ── Cotizaciones Altomayo — Diagnóstico innovación (LEAD-2025-008) ─
  {
    id: 'COT-2025-004',
    leadId: 'LEAD-2025-008',
    anio: 2025,
    mes: 'Marzo',
    dirigidoA: 'Patricia Ccopa Mamani',
    fechaCotizacion: new Date('2025-03-12'),
    cliente: 'Industrias Mayo S.A.C. (Altomayo)',
    producto: 'Diagnóstico de Innovación',
    servicio: 'Diagnóstico de capacidades tecnológicas y hoja de ruta de innovación para línea café specialty',
    monto: 6500,
    moneda: 'PEN',
    estado: 'aceptada',
    remitente: 'Administración',
    observacion: 'Incluye dos visitas técnicas a planta y entrega de informe con roadmap de innovación.',
    creadoEn: new Date('2025-03-12'),
  },

  // ── Cotizaciones Cacao de Aroma — Certificación (LEAD-2025-010) ────
  {
    id: 'COT-2024-002',
    leadId: 'LEAD-2025-010',
    anio: 2024,
    mes: 'Octubre',
    dirigidoA: 'Milagros Panduro Reátegui',
    fechaCotizacion: new Date('2024-10-05'),
    cliente: 'Cacao de Aroma S.A.C.',
    producto: 'Consultoría de Trazabilidad',
    servicio: 'Diagnóstico de trazabilidad y preparación para certificación Fine Cacao and Chocolate',
    monto: 7200,
    moneda: 'PEN',
    estado: 'aceptada',
    remitente: 'Ana Rojas',
    observacion: 'Certificación obtenida. Cliente incrementó precio FOB en 30% con compradores alemanes.',
    linkPropuesta: 'https://drive.google.com/cot-cacao-trazabilidad-2024',
    creadoEn: new Date('2024-10-05'),
  },

  // ── Cotizaciones Inversiones Pisco (LEAD-2025-005) ──────────────────
  {
    id: 'COT-2025-005',
    leadId: 'LEAD-2025-005',
    anio: 2025,
    mes: 'Abril',
    dirigidoA: 'Rafael Benavides Sotelo',
    fechaCotizacion: new Date('2025-04-12'),
    cliente: 'Inversiones Pisco S.A.',
    producto: 'Consultoría Tributaria',
    servicio: 'Calificación de proyectos de mejora tecnológica bajo Ley 30309 — I+D+i en destilería',
    monto: 11000,
    moneda: 'PEN',
    estado: 'enviada',
    remitente: 'Luis Torres',
    observacion: 'Incluye identificación de 3 proyectos calificables y elaboración de expedientes técnicos.',
    creadoEn: new Date('2025-04-12'),
  },

  // ── Cotizaciones AgroTech Innova (LEAD-2025-012) ────────────────────
  {
    id: 'COT-2025-006',
    leadId: 'LEAD-2025-012',
    anio: 2025,
    mes: 'Abril',
    dirigidoA: 'Fiorella Ríos Castillo',
    fechaCotizacion: new Date('2025-04-18'),
    cliente: 'AgroTech Innova',
    producto: 'Formulación de proyectos',
    servicio: 'Formulación de propuesta técnica y plan de negocio para STARTUP PERÚ Gen 14',
    monto: 4800,
    moneda: 'PEN',
    estado: 'aceptada',
    remitente: 'Luis Torres',
    observacion: 'Incluye propuesta técnica, plan de negocios y pitch deck. Postulación: 30 jun 2025.',
    creadoEn: new Date('2025-04-18'),
  },
];


// ──────────────────────────────────────────────
// USUARIOS (ROLES)
// ──────────────────────────────────────────────
export type CRMUser = {
  id: number;
  name: string;
  email: string;
  active: boolean;
  lastLogin: string;
  rol: 'Administrador' | 'Trabajador';
};

export const mockUsers: CRMUser[] = [
  { id: 1, name: 'Karien Diaz',     email: 'karien@bioactiva.pe',    active: true,  lastLogin: 'Hoy 09:15',   rol: 'Trabajador' },
  { id: 2, name: 'Administración',  email: 'admin@bioactiva.pe',     active: true,  lastLogin: 'Hoy 08:40',   rol: 'Administrador' },
  { id: 3, name: 'Ana Rojas',       email: 'arojas@bioactiva.pe',    active: true,  lastLogin: 'Ayer 17:30',  rol: 'Trabajador' },
  { id: 4, name: 'Luis Torres',     email: 'ltorres@bioactiva.pe',   active: true,  lastLogin: 'Hoy 10:00',   rol: 'Trabajador' },
  { id: 5, name: 'María Quispe',    email: 'mquispe@bioactiva.pe',   active: true,  lastLogin: 'Hace 2 días', rol: 'Trabajador' },
  { id: 6, name: 'Carlos Mamani',   email: 'cmamani@bioactiva.pe',   active: true,  lastLogin: 'Hoy 07:55',   rol: 'Trabajador' },
  { id: 7, name: 'Rosa Condori',    email: 'rcondori@bioactiva.pe',  active: false, lastLogin: 'Hace 1 sem.', rol: 'Trabajador' },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    tipo: 'lead_asignado',
    titulo: 'Nuevo lead asignado',
    mensaje: 'Se te ha asignado el lead de Altomayo.',
    fecha: new Date('2026-05-01'),
    leida: false,
    destinatario: { tipo: 'usuario', userId: 'karien@bioactiva.pe' },
    linkUrl: '/pipeline'
  },
  {
    id: 'notif-002',
    tipo: 'alerta_admin',
    titulo: 'Revisión de metas del mes',
    mensaje: 'Por favor revisar el reporte de ventas mensual.',
    fecha: new Date('2026-05-02'),
    leida: false,
    destinatario: { tipo: 'rol', rol: 'Administrador' },
    linkUrl: '/profile'
  },
  {
    id: 'notif-003',
    tipo: 'general',
    titulo: 'Nuevo CRM habilitado',
    mensaje: 'El nuevo sistema CRM de Bioactiva ya está activo.',
    fecha: new Date('2026-05-03'),
    leida: true,
    destinatario: { tipo: 'global' },
    linkUrl: '/'
  }
];
